# Generated by Django 3.1.4 on 2021-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
