version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sprints_local_django
    depends_on:
      - postgres
      - redis
      - celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sprints_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
      - ./.env

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: sprints_local_celeryworker
    depends_on:
      - redis
      - postgres
      - celerybeat
    environment:
      - COLUMNS=80  # https://github.com/celery/celery/issues/5761

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sprints_local_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat
    environment:
      - COLUMNS=80  # https://github.com/celery/celery/issues/5761

  flower:
    <<: *django
    image: sprints_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
