#!/bin/sh

set -o errexit
set -o nounset


pip install "celery<5"  # https://github.com/mher/flower/issues/1029
celery flower \
    --app=config.celery_app \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
